[project]
name = "forced-thoughts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.3.1",
    "openai>=1.63.2",
]
